# Use the MySQL 8.3.0 base image
FROM mysql:8.3.0

# Environment variables
ENV MYSQL_DATABASE=hw1
ENV MYSQL_USER=user
ENV MYSQL_PASSWORD=password
ENV MYSQL_ROOT_PASSWORD=adminpassword

# Expose the MySQL port
EXPOSE 3306

# Start MySQL service
CMD ["mysqld"]
