package io.github.bonigarcia.webdriver;
import static org.assertj.core.api.Assertions.assertThat;
// Generated by Selenium IDE
import org.openqa.selenium.By;
import org.openqa.selenium.chrome.ChromeDriver;

import io.github.bonigarcia.seljup.SeleniumJupiter;

import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;


@ExtendWith(SeleniumJupiter.class)
public class BuyTripTestSeleniumExtension {

  @Test
  void buyTrip(ChromeDriver driver) {
    driver.get("https://blazedemo.com/");
    driver.manage().window().setSize(new Dimension(1850, 1053));
    driver.findElement(By.name("fromPort")).click();
    {
      WebElement dropdown = driver.findElement(By.name("fromPort"));
      dropdown.findElement(By.xpath("//option[. = 'Boston']")).click();
    }
    driver.findElement(By.name("toPort")).click();
    {
      WebElement dropdown = driver.findElement(By.name("toPort"));
      dropdown.findElement(By.xpath("//option[. = 'London']")).click();
    }
    driver.findElement(By.cssSelector(".btn-primary")).click();
    driver.findElement(By.cssSelector("tr:nth-child(1) > td:nth-child(2)")).click();
    driver.findElement(By.id("inputName")).click();
    driver.findElement(By.id("inputName")).sendKeys("Tiago");
    driver.findElement(By.id("address")).sendKeys("Rua2");
    driver.findElement(By.id("city")).sendKeys("Aveiro");
    driver.findElement(By.id("zipCode")).sendKeys("1233-123");
    driver.findElement(By.id("creditCardNumber")).sendKeys("123123123");
    driver.findElement(By.id("nameOnCard")).sendKeys("Tiago Smth");
    driver.findElement(By.cssSelector(".btn-primary")).click();
    assertThat(driver.getTitle().equals("BlazeDemo Confirmation"));
  }
}
