name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    if: "contains(github.event.head_commit.message, 'hw1')"
    defaults:
      run:
        working-directory: hw1 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Install Chrome for Testing and its driver
      run: |
        npm i puppeteer
        npx @puppeteer/browsers install chrome@stable
    - name: List Directory Files for Debug
      run: ls -a
    - name: Set executable permissions for compile.sh
      run: chmod +x compile.sh
    - name: Deploy Mysql
      run: ./compile.sh mysql hw1
    - name: Set executable permissions for test.sh
      run: chmod +x test.sh
    - name: Test Application
      run: ./test.sh
